apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-test
spec:
  containers:
    - name: memory-demo-ctr
      image: polinux/stress
      resources:
        requests:
          memory: "1000Mi"
          cpu: "100m"
        limits:
          memory: "2000Mi"
          cpu: "150m"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
