name: Notify on Specific File Change

on:
  push:
    branches:
      - main
    paths:
      - linux/alias/kubernetes/kubectl-aliases/generate_aliases.py

jobs:
  rebuild-workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug
        run: |
          pwd
          ls -al
          python3 --version