import subprocess

# Define variable
generate_alias_script = './linux/alias/kubernetes/kubectl-aliases/generate_aliases.py'
target_file = './linux/alias/kubernetes/kubectl-aliases/.kubectl_aliases'
start_marker = '/** START: Autogenerated by generate_aliases.py **/'
end_marker = '/** END: Autogenerated by generate_aliases.py **/'
# Run the command and get the output
result = subprocess.run(['python3', generate_alias_script], stdout=subprocess.PIPE, text=True)
content = result.stdout

# Read the .kubectl_aliases file
with open(target_file, 'r') as file:
    lines = file.readlines()

start_index = None
end_index = None

for i, line in enumerate(lines):
    if start_marker in line:
        start_index = i
    if end_marker in line:
        end_index = i

# Replace the content between the markers
if start_index is not None and end_index is not None:
    new_lines = "\n" + lines[:start_index + 1] + [content] + lines[end_index:] + "\n"
else:
    print("Markers not found in the file.")
    exit(1)

# Write the updated content back to the file
with open(target_file, 'w') as file:
    file.writelines(new_lines)