network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: false
      dhcp6: false
      dhcp-identifier: mac 
      addresses:
      - 192.168.1.122/24
      routes:
      - to: default
        via: 192.168.8.2
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]