apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-debug
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/bash", "-c", "sleep infinity"] # Keep the pod running
      volumeMounts:
        - mountPath: /mnt/data
          name: ubuntu-storage
  volumes:
    - name: ubuntu-storage
      persistentVolumeClaim:
        claimName: ubuntu-pvc
