apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-pv
spec:
  capacity:
    storage: 450Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /path/on/host # Change this to a valid path on your host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 450Gi