apiVersion: v1
kind: Pod
metadata:
  name: mssql-debug
spec:
  containers:
    - name: mssql-tools
      image: mcr.microsoft.com/mssql-tools
      command: ["/bin/bash", "-c", "sleep infinity"] # Keep the pod running
      volumeMounts:
        - mountPath: /mnt/data
          name: mssql-storage
  volumes:
    - name: mssql-storage
      persistentVolumeClaim:
        claimName: mssql-pvc
