name: Local Config
version: 1.0.0
schema: v1
models:
  - name: GPT 5.5
    description: A powerful AI model for chat and autocomplete tasks.
    provider: openai
    model: gpt-5.5
    apiBase: https://vsllm.com/v1
    apiKey: <API_KEY>
    roles:
      - chat
      - autocomplete
context:
  - provider: folder
  - provider: diff
  - provider: docs
  - provider: tree
  - provider: problems
  - provider: os
