apiVersion: v1
kind: Pod
metadata:
  name: affinity-test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  tolerations: 
  - key: "app=dxp-united-oss"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"