apiVersion: v1
kind: Pod
metadata:
  name: crash-loop-pod
spec:
  containers:
    - name: crash-container
      image: busybox
      command: ["sh", "-c", "exit 1"] # Crash with an error exit code
  restartPolicy: Always
