apiVersion: v1
kind: Pod
metadata:
  name: affinity-test
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  tolerations:
    - key: "<node-taint-key>"
      operator: "Equal"
      value: "<node-taint-value>"
      effect: "NoSchedule"
