apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-debug
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ["/bin/bash", "-c", "sleep infinity"] # Keep the pod running
      volumeMounts:
        - mountPath: /mnt/data
          name: ubuntu-storage
      # resources:
      #   requests:
      #     memory: "2Gi"
      #     cpu: "1"
      #   limits:
      #     memory: "3Gi"
      #     cpu: "2"
  volumes:
    - name: ubuntu-storage
      persistentVolumeClaim:
        claimName: ubuntu-pvc
  tolerations:
    - key: "spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "workload"
      operator: "Equal"
      value: "spark-executor"
      effect: "NoSchedule"