name: Build Workspace

on:
  push:
    branches:
      - main
    paths:
      - linux/alias/kubernetes/kubectl-aliases/generate_aliases.py
      - linux/alias/git/git_aliases.txt
      - .github/workflows/build-workspace.yaml

jobs:
  rebuild-workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run rebuild Kubectl alias script
        run: |
          echo "[Rebuild worspace] Kubectl aliases"
          python3 ./.github/scripts/rebuild-workspace--kubectl-aliases.py

      - name: Run rebuild Git alias script
        run: |
          echo "[Rebuild worspace] Git aliases"
          mv ./linux/alias/git/git_aliases.txt .
          python3 ./linux/alias/git/generate_aliases.py
          python3 ./.github/scripts/rebuild-workspace--git-aliases.py
          rm .git_aliases_temp
        
      - name: Verify .kubectl_aliases output file
        run: |
          cat ./linux/alias/kubernetes/kubectl-aliases/.kubectl_aliases
      
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update kubectl & git aliases"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}