name: "[1.0] Verify Tools Installation"

on:
  # push:
  #   branches:
  #     - main

  # schedule:
  #   # Runs at 07:00 AM in every month.
  #   - cron: "0 17 */1 * *"

  # Optional: You can also allow manual runs
  workflow_dispatch:
    inputs:
      shell_type:
        description: "Choose Shell Type"
        required: false
        default: "bash"
        type: choice
        options:
          - bash
          - zsh

jobs:
  verify-configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Input
        run: |
          echo "Shell Type: ${{ github.event.inputs.shell_type }}"

  annacoda-install:
    runs-on: ubuntu-latest
    needs: verify-configuration
    steps:
      - name: Execute Installation
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/annacoda.sh | bash

  summary-results:
    runs-on: ubuntu-latest
    if: always()
    needs: [annacoda-install]
    steps:
      - name: Cleanup resources
        run: |
          echo "Summary Result"
